// ========== EXPANDED JOB DATABASE WITH ALL CAMEROON SOURCES ==========
const jobDatabase = [
    // ===== LINKEDIN CAMEROON JOBS =====
    {
        id: 'job-0',
        title: 'Senior Software Developer',
        company: 'Orange Cameroon',
        location: 'Douala',
        type: 'Full-time',
        posted: '2 days ago',
        source: 'cm.Linkedin.com',
        sourceUrl: 'https://cm.linkedin.com/jobs',
        keywords: ['developer', 'software', 'programmer', 'coding', 'javascript', 'python', 'java', 'react', 'angular', 'node', 'full stack', 'backend', 'frontend'],
        description: `Orange Cameroon is seeking a Senior Software Developer to lead our digital transformation initiatives in Douala...`,
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science', '5+ years experience', 'Strong problem-solving skills'],
        deadline: 'April 15, 2024',
        experience: '5-8 years',
        education: 'Master\'s Degree preferred',
        benefits: ['Competitive salary', 'Health insurance', '13th month', 'Transport allowance', 'Remote work options'],
        matchScore: 0
    },
    {
        title: 'Marketing Manager',
        company: 'MTN Cameroon',
        location: 'Yaoundé',
        type: 'Full-time',
        posted: '1 week ago',
        source: 'cm.Linkedin.com',
        sourceUrl: 'https://cm.linkedin.com/jobs',
        keywords: ['marketing', 'manager', 'brand', 'advertising', 'campaign', 'digital', 'social media'],
        description: `MTN Cameroon is seeking an experienced Marketing Manager to lead our marketing initiatives in Yaoundé...`,
        requirements: ['Bachelor\'s degree in Marketing', '5+ years experience', 'Strong leadership skills'],
        deadline: 'April 20, 2024',
        experience: '5-8 years',
        education: 'Bachelor\'s/MBA',
        benefits: ['Competitive package', 'Performance bonus', 'Company car', 'Health insurance'],
        matchScore: 0
    },
    // ===== EXPERTINI CAMEROON JOBS =====
    {
        title: 'Data Scientist',
        company: 'Expertini Cameroon',
        location: 'Douala',
        type: 'Full-time',
        posted: '3 days ago',
        source: 'cm.expertini.com',
        sourceUrl: 'https://cm.expertini.com',
        keywords: ['data', 'scientist', 'analytics', 'python', 'r', 'sql', 'machine learning', 'ai'],
        description: `Expertini is looking for a Data Scientist to join our analytics team in Douala...`,
        requirements: ['Master\'s in Data Science', '3+ years experience', 'Python, SQL, ML'],
        deadline: 'April 18, 2024',
        experience: '3-5 years',
        education: 'Master\'s Degree',
        benefits: ['Competitive salary', 'Health insurance', 'Training budget'],
        matchScore: 0
    },
    // ===== RECRUIT.NET CAMEROON JOBS =====
    {
        title: 'Project Manager',
        company: 'Recruit.net Cameroon',
        location: 'Yaoundé',
        type: 'Full-time',
        posted: '5 days ago',
        source: 'recruit.net',
        sourceUrl: 'https://recruit.net/cameroon',
        keywords: ['project manager', 'construction', 'infrastructure', 'building'],
        description: `Leading construction company seeks Project Manager for infrastructure projects in Yaoundé...`,
        requirements: ['Engineering degree', 'PMP certification', '7+ years experience'],
        deadline: 'April 25, 2024',
        experience: '7-10 years',
        education: 'Engineering Degree + PMP',
        benefits: ['Competitive package', 'Project bonuses', 'Company car'],
        matchScore: 0
    },
    // ===== JOBVACAN.COM JOBS =====
    {
        title: 'Customer Service Representative',
        company: 'Jobvacan',
        location: 'Douala',
        type: 'Full-time',
        posted: 'Today',
        source: 'jobvacan.com',
        sourceUrl: 'https://jobvacan.com',
        keywords: ['customer service', 'support', 'call center', 'client'],
        description: `Jobvacan is seeking Customer Service Representatives for a leading telecom company in Douala...`,
        requirements: ['High school diploma', 'Good communication', 'Bilingual preferred'],
        deadline: 'April 5, 2024',
        experience: 'Entry Level',
        education: 'High School +',
        benefits: ['Competitive salary', 'Training', 'Performance bonuses'],
        matchScore: 0
    },
    // ===== UNJOBNET.ORG JOBS =====
    {
        title: 'Program Officer - Education',
        company: 'UNICEF Cameroon',
        location: 'Yaoundé',
        type: 'Contract',
        posted: '1 week ago',
        source: 'unjobnet.org',
        sourceUrl: 'https://unjobnet.org',
        keywords: ['un', 'unicef', 'international', 'ngo', 'program', 'officer', 'education'],
        description: `UNICEF Cameroon is seeking a Program Officer for our Education section...`,
        requirements: ['Master\'s in Education', '3+ years experience', 'UN experience preferred'],
        deadline: 'April 30, 2024',
        experience: '3-5 years',
        education: 'Master\'s Degree',
        benefits: ['International salary scale', 'Housing allowance', 'Education grant'],
        matchScore: 0
    },
    {
        title: 'Monitoring & Evaluation Officer',
        company: 'World Bank Cameroon',
        location: 'Yaoundé',
        type: 'Consultant',
        posted: '3 days ago',
        source: 'unjobnet.org',
        sourceUrl: 'https://unjobnet.org',
        keywords: ['monitoring', 'evaluation', 'm&e', 'data', 'world bank', 'development'],
        description: `The World Bank Cameroon office is looking for a Monitoring & Evaluation Officer...`,
        requirements: ['Master\'s in Economics', '5+ years M&E experience', 'World Bank procedures'],
        deadline: 'April 22, 2024',
        experience: '5-8 years',
        education: 'Master\'s Degree',
        benefits: ['Consultant daily rate', 'Travel insurance'],
        matchScore: 0
    },
    // ===== EXPRESSCAREERS.DHL.COM JOBS =====
    {
        title: 'Logistics Coordinator',
        company: 'DHL Cameroon',
        location: 'Douala',
        type: 'Full-time',
        posted: '2 days ago',
        source: 'expresscareers.dhl.com',
        sourceUrl: 'https://expresscareers.dhl.com',
        keywords: ['logistics', 'supply chain', 'coordinator', 'dhl', 'transport'],
        description: `DHL Cameroon is seeking a Logistics Coordinator to manage our supply chain operations in Douala...`,
        requirements: ['Degree in Logistics', '3+ years experience', 'Supply chain knowledge'],
        deadline: 'April 12, 2024',
        experience: '3-5 years',
        education: 'Bachelor\'s Degree',
        benefits: ['Competitive salary', 'Health insurance', 'Transport allowance'],
        matchScore: 0
    },
    // ===== LOUMA-JOBS.COM JOBS =====
    {
        title: 'Sales Representative',
        company: 'Louma Jobs',
        location: 'Buea',
        type: 'Full-time',
        posted: '4 days ago',
        source: 'louma-jobs.com',
        sourceUrl: 'https://louma-jobs.com',
        keywords: ['sales', 'representative', 'business development', 'client'],
        description: `Louma Jobs is seeking motivated Sales Representatives for our client in Buea...`,
        requirements: ['Bachelor\'s in Business', '1-3 years sales', 'Valid driver\'s license'],
        deadline: 'April 10, 2024',
        experience: '1-3 years',
        education: 'Bachelor\'s Degree',
        benefits: ['Commission structure', 'Company vehicle', 'Health insurance'],
        matchScore: 0
    },
    // ===== OBOULOT.IO JOBS =====
    {
        title: 'Web Developer',
        company: 'Oboulot.io',
        location: 'Remote',
        type: 'Remote',
        posted: 'Today',
        source: 'oboulot.io',
        sourceUrl: 'https://oboulot.io',
        keywords: ['web', 'developer', 'frontend', 'backend', 'javascript', 'react', 'node'],
        description: `Oboulot.io is looking for a Web Developer to work on exciting projects remotely...`,
        requirements: ['2+ years experience', 'JavaScript, React', 'Portfolio'],
        deadline: 'April 8, 2024',
        experience: '2-4 years',
        education: 'Any',
        benefits: ['Remote work', 'Flexible hours', 'Competitive pay'],
        matchScore: 0
    },
    // ===== CAMEROONJOBS.NET JOBS =====
    {
        title: 'Accountant',
        company: 'CameroonJobs.net',
        location: 'Douala',
        type: 'Full-time',
        posted: '3 days ago',
        source: 'cameroonjobs.net',
        sourceUrl: 'https://cameroonjobs.net',
        keywords: ['accountant', 'accounting', 'finance', 'tax', 'audit'],
        description: `CameroonJobs.net is recruiting an Accountant for a reputable company in Douala...`,
        requirements: ['Bachelor\'s in Accounting', '3+ years', 'CPA preferred'],
        deadline: 'April 15, 2024',
        experience: '3-5 years',
        education: 'Bachelor\'s + CPA',
        benefits: ['Competitive salary', 'Health insurance', '13th month'],
        matchScore: 0
    },
    // ===== CAMEROONDESKS.COM JOBS =====
    {
        title: 'Graduate Trainee Program',
        company: 'Cameroondesks.com',
        location: 'Yaoundé',
        type: 'Internship',
        posted: '1 week ago',
        source: 'cameroondesks.com',
        sourceUrl: 'https://cameroondesks.com',
        keywords: ['graduate', 'trainee', 'internship', 'fresh graduate', 'entry level'],
        description: `Cameroondesks.com is offering a Graduate Trainee Program for recent graduates across various fields...`,
        requirements: ['Bachelor\'s degree', '0-1 year experience', 'Good academic record'],
        deadline: 'April 20, 2024',
        experience: 'Entry Level',
        education: 'Bachelor\'s Degree',
        benefits: ['Stipend', 'Training', 'Mentorship', 'Certificate'],
        matchScore: 0
    },
    {
        title: 'Fully-Funded Scholarship - Masters in Public Health',
        company: 'Cameroondesks.com',
        location: 'International',
        type: 'Scholarship',
        posted: '5 days ago',
        source: 'cameroondesks.com',
        sourceUrl: 'https://cameroondesks.com',
        keywords: ['scholarship', 'masters', 'public health', 'fully funded', 'study abroad'],
        description: `Fully-funded scholarship for Masters in Public Health at a top university. Open to Cameroonian students...`,
        requirements: ['Bachelor\'s degree', 'Good grades', 'English proficiency'],
        deadline: 'May 15, 2024',
        experience: 'Any',
        education: 'Bachelor\'s Degree',
        benefits: ['Full tuition', 'Living stipend', 'Travel costs', 'Health insurance'],
        matchScore: 0
    },
    // ===== AKWAJOBS.COM JOBS =====
    {
        title: 'Primary School Teacher',
        company: 'Akwajobs Buea',
        location: 'Buea',
        type: 'Full-time',
        posted: '2 days ago',
        source: 'akwajobs.com',
        sourceUrl: 'https://akwajobs.com',
        keywords: ['teacher', 'teaching', 'education', 'primary school', 'buea'],
        description: `Akwajobs is recruiting a Primary School Teacher for a reputable school in Buea...`,
        requirements: ['Teaching qualification', '2+ years experience', 'Bilingual preferred'],
        deadline: 'April 7, 2024',
        experience: '2-4 years',
        education: 'Teaching Diploma',
        benefits: ['Competitive salary', 'Housing allowance', 'School holidays'],
        matchScore: 0
    },
    {
        title: 'Nurse',
        company: 'Akwajobs Douala',
        location: 'Douala',
        type: 'Full-time',
        posted: '3 days ago',
        source: 'akwajobs.com',
        sourceUrl: 'https://akwajobs.com',
        keywords: ['nurse', 'nursing', 'healthcare', 'medical', 'hospital'],
        description: `Akwajobs is seeking a Registered Nurse for a private clinic in Douala...`,
        requirements: ['Nursing diploma', 'Valid license', '1+ year experience'],
        deadline: 'April 9, 2024',
        experience: '1-3 years',
        education: 'Nursing Diploma',
        benefits: ['Competitive salary', 'Shift allowances', 'Health insurance'],
        matchScore: 0
    },
    // ===== OMNIJOBER FREELANCE JOBS =====
    {
        title: 'Freelance Graphic Designer',
        company: 'Omnijobber',
        location: 'Remote',
        type: 'Freelance',
        posted: 'Today',
        source: 'Omnijobber',
        sourceUrl: 'https://omnijobber.com',
        keywords: ['freelance', 'graphic design', 'photoshop', 'illustrator', 'designer'],
        description: `Omnijobber is looking for freelance Graphic Designers for various projects. Work remotely and set your own hours...`,
        requirements: ['Portfolio', 'Adobe Creative Suite', 'Creative mindset'],
        deadline: 'Rolling basis',
        experience: 'Any',
        education: 'Any',
        benefits: ['Flexible hours', 'Work from home', 'Choose your projects'],
        matchScore: 0
    },
    {
        title: 'Freelance Content Writer',
        company: 'Omnijobber',
        location: 'Remote',
        type: 'Freelance',
        posted: 'Yesterday',
        source: 'Omnijobber',
        sourceUrl: 'https://omnijobber.com',
        keywords: ['freelance', 'writer', 'content', 'copywriting', 'blogging'],
        description: `Omnijobber seeks freelance Content Writers for web content, blog posts, and articles...`,
        requirements: ['Excellent English', 'Writing portfolio', 'Research skills'],
        deadline: 'Rolling basis',
        experience: 'Any',
        education: 'Any',
        benefits: ['Flexible schedule', 'Remote work', 'Performance bonuses'],
        matchScore: 0
];

// Assign unique IDs to all jobs if not present
jobDatabase.forEach((job, index) => {
    if (!job.id) job.id = `job-${index}`;
});
